Release Version 24.03.0.3
Pandora-IsoMemo/bpred pull request #45
Opened 2024-04-16 15:01 UTC by arunge

## Version: 24.03.0

### Updates
- integration of modules from shinyTools: dataExport, plotExport (#36)

2024-04-16 15:23 UTC, jan-abel-inwt requested changes
Maybe updating shinyMatrix to 0.8.0 should fix the checks

2024-04-16 15:23 UTC, jan-abel-inwt commented on DESCRIPTION
>    DataTools (>= 24.03.0.2),
sollten wir hier auf die neuste Version gehen: `24.04.2` ?

2024-04-16 15:23 UTC, jan-abel-inwt commented on DESCRIPTION
>    modules,
ich kann es gerade nicht markieren.
shinyMatrix muss auf 0.8.0 gesetzt werden. Auf CRAN wurde eine Version übersprungen und deshalb ist 0.7.0 nicht verfügbar

2024-04-17 07:16 UTC, arunge commented
@jan-abel-inwt shiny-matrix seems to be not available:
![image](https://github.com/Pandora-IsoMemo/bpred/assets/16759098/6dc3fb8d-d2b0-417c-ab84-8254289af27d)

2024-04-17 08:41 UTC, jan-abel-inwt commented
We need to deploy shinyMatrix 0.8.0 to the INWTlab drat Repo, because the timestamp of the mpi base-image is to old.

2024-04-30 09:06 UTC, merged